
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Geoffery10", email = "powellgeoffery@gmail.com"},
]
dependencies = [
    "discord-py>=2.3.0",
    "asyncio>=3.4.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.scripts]
run = "python -m main"
test = "pytest"
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
]
