name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
      - name: Update packages
        run: pdm update
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm test
