name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
      - name: Install dependencies
        run: pdm install
      - name: Run tests with coverage
        run: pdm run pytest --cov=. --cov-report xml
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
